### PR TITLE
update packager-keyids to use Artix Buildbot sub key

### PR DESCRIPTION
**Pull request by thefallenrat**
In `20170805-1` version of `artix-keyring` package, installing it will only give you the key of Cromnix Buildbot..

Excerpt from the logs : 

```
(1/1) reinstalling artix-keyring
==> Appending keys from artix.gpg...
==> Locally signing trusted keys in keyring...
  -> Locally signing key 8AC1470E584E6AAB0BBBAC3FED587B6247A4152D...
  -> Locally signing key 2C69BCE8163847BC56401FD2CF18A351C0705F6A...
  -> Locally signing key 664187F32A958D0ED06530067BFAD0C0864DA8E8...
  -> Locally signing key 80E461C30BE40AD3EFB57E18EA690BC73A4F1094...
==> Importing owner trust values...
==> Updating trust database...
gpg: next trustdb check due at 2018-06-01

~/git-projects/artix-keyring >>> pacman-key --list-keys Buildbot
gpg: Note: trustdb not writable
pub   rsa4096 2017-06-18 [SC]
      0A3EB6BB142C56653300420C1247D995F165BBAC
uid           [  full  ] Cromnix (Buildbot) <cromnix@cromnix.org>
sub   rsa4096 2017-06-18 [E]
```

The only workaround for this was to refresh the key and locally sign it : 

```
~ >>> sudo pacman-key --refresh-keys Buildbot
gpg: refreshing 1 key from hkp://ipv4.pool.sks-keyservers.net:11371
key 1247D995F165BBAC:
1 signature not checked due to a missing key
gpg: key 1247D995F165BBAC: "Artix Buildbot <buildbot@artixlinux.org>" 1 new user ID
gpg: key 1247D995F165BBAC: "Artix Buildbot <buildbot@artixlinux.org>" 6 new signatures
gpg: Total number processed: 1
gpg:           new user IDs: 1
gpg:         new signatures: 6
gpg: marginals needed: 3  completes needed: 1  trust model: pgp
gpg: depth: 0  valid:   1  signed:  30  trust: 0-, 0q, 0n, 0m, 0f, 1u
gpg: depth: 1  valid:  30  signed:  79  trust: 1-, 0q, 0n, 29m, 0f, 0u
gpg: depth: 2  valid:  72  signed:  12  trust: 72-, 0q, 0n, 0m, 0f, 0u
gpg: next trustdb check due at 2018-06-01
~ >>> pacman-key --list-keys Buildbot
gpg: Note: trustdb not writable
pub   rsa4096 2017-06-18 [SC]
      0A3EB6BB142C56653300420C1247D995F165BBAC
uid           [marginal] Artix Buildbot <buildbot@artixlinux.org>
sub   rsa4096 2017-06-18 [E]

~ >>> sudo pacman-key --lsign-key Buildbot
  -> Locally signing key Buildbot...
==> Updating trust database...
gpg: marginals needed: 3  completes needed: 1  trust model: pgp
gpg: depth: 0  valid:   1  signed:  31  trust: 0-, 0q, 0n, 0m, 0f, 1u
gpg: depth: 1  valid:  31  signed:  79  trust: 2-, 0q, 0n, 29m, 0f, 0u
gpg: depth: 2  valid:  72  signed:  12  trust: 72-, 0q, 0n, 0m, 0f, 0u
gpg: next trustdb check due at 2018-06-01
```

Therefore to fix this once and for all, I opened a pull request with commit that changes of the file `packager-keyids` to use Artix sub key

Thanks!

### CODE REVIEW

**Comment by cromerc** [comment]
You shouldn't modify the .asc files by hand. They are automatically generated when you run update-keys included in this repo. The file you should edit is packager-keyids that file is what contains the keys that need to be generated.

**Comment by thefallenrat** [comment]
> You shouldn't modify the .asc files by hand. They are automatically generated when you run update-keys included in this repo. The file you should edit is packager-keyids that file is what contains the keys that need to be generated.

But both Cromnix Buildbot and Artix Buildbot has the same keyids, so I don't know what should I change in `packager-keyids`

https://github.com/artix-linux/artix-keyring/blob/7257b16108fdd424ac1974f1f6fe16edc1f94d29/packager-keyids#L5
```
pacman-key --list-keys 0A3EB6BB142C56653300420C1247D995F165BBAC

gpg: Note: trustdb not writable
pub   rsa4096 2017-06-18 [SC]
      0A3EB6BB142C56653300420C1247D995F165BBAC
uid           [  full  ] Artix Buildbot <buildbot@artixlinux.org>
sub   rsa4096 2017-06-18 [E]
```

And running `./update-keys` delete almost all `.asc` files, leaving `1FBCAF27A69E29B6` as master key only

```
gpg: Generating Artix Keyring keychain master key...
gpg: key 1FBCAF27A69E29B6 marked as ultimately trusted
gpg: Done
gpg: key "664187F32A958D0ED06530067BFAD0C0864DA8E8" not found: No public key
gpg: WARNING: nothing exported
gpg: key "8AC1470E584E6AAB0BBBAC3FED587B6247A4152D" not found: No public key
gpg: WARNING: nothing exported
gpg: key "2C69BCE8163847BC56401FD2CF18A351C0705F6A" not found: No public key
gpg: WARNING: nothing exported
gpg: key "80E461C30BE40AD3EFB57E18EA690BC73A4F1094" not found: No public key
gpg: WARNING: nothing exported
gpg: key "A55C3F1BA61CAA63036D82BAFA91071797BEEEC2" not found: No public key
key is not fully trusted: A55C3F1BA61CAA63036D82BAFA91071797BEEEC2 cromer
gpg: key "78C9C713EAD7BEC69087447332E21894258C6105" not found: No public key
key is not fully trusted: 78C9C713EAD7BEC69087447332E21894258C6105 artoo
gpg: key "5C4F42BE7CCA73D5C591C32900077735933C3778" not found: No public key
key is not fully trusted: 5C4F42BE7CCA73D5C591C32900077735933C3778 damnwidget
gpg: key "98AE6E32AE0A4D126EACAC8C6023C3BEEAB08C4A" not found: No public key
key is not fully trusted: 98AE6E32AE0A4D126EACAC8C6023C3BEEAB08C4A nous
gpg: key "0A3EB6BB142C56653300420C1247D995F165BBAC" not found: No public key
key is not fully trusted: 0A3EB6BB142C56653300420C1247D995F165BBAC buildbot
cat: 'master-revoked/*.asc': No such file or directory
cat: 'packager/*.asc': No such file or directory
cat: 'packager-revoked/*.asc': No such file or directory
```

**Comment by cromerc** [comment]
They should have different fingerprints, from what I am reading the fingerprint for the subkey can be seen with --with-subkey-fingerprints argument.
I will take a look tomorrow morning to find the correct keyid for the artixbuild bot subkey.

**Comment by thefallenrat** [comment]
Found it : 

```
gpg --recv-keys --keyserver hkp://pgp.mit.edu 0A3EB6BB142C56653300420C1247D995F165BBAC

key 1247D995F165BBAC:
7 signatures not checked due to missing keys
gpg: key 1247D995F165BBAC: public key "Artix Buildbot <buildbot@artixlinux.org>" imported
gpg: marginals needed: 3  completes needed: 1  trust model: pgp
gpg: depth: 0  valid:   1  signed:   1  trust: 0-, 0q, 0n, 0m, 0f, 1u
gpg: depth: 1  valid:   1  signed:   0  trust: 1-, 0q, 0n, 0m, 0f, 0u
gpg: next trustdb check due at 2018-01-19
gpg: Total number processed: 1
gpg:               imported: 1

---

gpg --finger --with-subkey-fingerprints Buildbot

pub   rsa4096 2017-06-18 [SC]
      0A3E B6BB 142C 5665 3300  420C 1247 D995 F165 BBAC
uid           [ unknown] Artix Buildbot <buildbot@artixlinux.org>
sub   rsa4096 2017-06-18 [E]
      3C6A 295D 5E74 F8C0 5AE6  3E98 0732 C0B8 56D1 9AB4
```

Will update pull request shortly

**Comment by thefallenrat** [comment]
Now that I have managed to change the fingerprint of buildbot (and figured it out why running `./update-keys` gives no keys exported (it was misconfigured keyserver)). I recommit the pull request to just change the `packager-keyids`

But after I changed the fingerprints, running `./update-keys` give me this : 

```
./update-keys
gpg: Generating Artix Keyring keychain master key...
gpg: key 99B3A393F7E90C73 marked as ultimately trusted
gpg: Done
key is not fully trusted: 98AE6E32AE0A4D126EACAC8C6023C3BEEAB08C4A nous
key is not fully trusted: 3C6A295D5E74F8C05AE63E980732C0B856D19AB4 buildbot
cat: 'master-revoked/*.asc': No such file or directory
cat: 'packager-revoked/*.asc': No such file or directory
```
I assume both nous and buildbot key needs to signed (either from itself (?) or others) so that it can be fully trusted

**Comment by artixnous** [comment]
That's a new one,  the ring of trust was signed by all master keys 3 months
ago.

**Comment by cromerc** [comment]
Maybe we all need to sign the artix subkey as well?

**Comment by thefallenrat** [comment]
> Maybe we all need to sign the artix subkey as well?

Maybe we should. Here is a comparison between Artix key and Cromnix Key

```

uid Artix Buildbot <buildbot@artixlinux.org>
sig  sig3  F165BBAC 2017-08-06 __________ __________ [selfsig]
sig  sig   C0705F6A 2017-08-06 __________ __________ Oscar Campos (Artix Master-Key) <damnwidget@artixlinux.org>

uid Cromnix (Buildbot) <cromnix@cromnix.org>
sig  sig3  F165BBAC 2017-06-18 __________ __________ [selfsig]
sig  sig   D341EB9B 2017-06-18 __________ __________ Cromnix (cromer) <cromer@cromnix.org>
sig  sig   CE8A6ABD 2017-06-18 __________ __________ Cromnix (Master) <cromnix@cromnix.org>
sig  sig   4C40536B 2017-06-19 __________ __________ Cromnix (artoo) <artoo@cromnix.org>
sig  sig   47A4152D 2017-08-06 __________ __________ Marcus von Ditfurth (Artix Master-Key) <artoo@artixlinux.org>
sig  sig   3A4F1094 2017-08-06 __________ __________ Christos Nouskas (Artix Master Key) <nous@artixlinux.org>
sig  sig   864DA8E8 2017-08-06 __________ __________ Chris Cromer (Artix Master-Key) <cromer@artixlinux.org>
sig revok  F165BBAC 2017-08-06 __________ __________ [selfsig]
```

**Comment by cromerc** [comment]
I have just signed the artix key, and damnwidget had signed it sometime in the past. @udeved @archnous please sign this key:
3C6A295D5E74F8C05AE63E980732C0B856D19AB4

Apparently we have to sign the subkey called artix as well. Before now we had only signed the cromnix key which we had signed before we changed its name to artix. After it has all 4 of our signatures I will push a new keyring.

**Comment by udeved** [comment]
@cromerc 

Will signed it later, busy right now.

We probably also include @thefallenrat key.

**Comment by thefallenrat** [comment]
> Apparently we have to sign the subkey called artix as well. Before now we had only signed the cromnix key which we had signed before we changed its name to artix. After it has all 4 of our signatures I will push a new keyring.

Okay. That's a good news for bot's key, but what about @nous key?

```
./update-keys

...
key is not fully trusted: 98AE6E32AE0A4D126EACAC8C6023C3BEEAB08C4A nous
...
```
I reckon it needs to be signed as well

```
uid Christos Nouskas (nous) <nous@artixlinux.org>
sig  sig3  EAB08C4A 2017-09-10 __________ 2019-09-18 [selfsig]
sig  sig3  EAB08C4A 2017-09-10 __________ 2019-09-18 [selfsig]
sig  sig3  EAB08C4A 2017-09-27 __________ __________ [selfsig]

uid Christos Nouskas (nous) <nous@archlinux.us>
sig  sig3  EAB08C4A 2016-09-18 __________ 2019-09-18 [selfsig]
sig  sig   47A4152D 2017-08-06 __________ __________ Marcus von Ditfurth (Artix Master-Key) <artoo@artixlinux.org>
sig  sig   864DA8E8 2017-08-06 __________ __________ Chris Cromer (Artix Master-Key) <cromer@artixlinux.org>
sig  sig   3A4F1094 2017-08-06 __________ __________ Christos Nouskas (Artix Master Key) <nous@artixlinux.org>
sig  sig   C0705F6A 2017-08-06 __________ __________ Oscar Campos (Artix Master-Key) <damnwidget@artixlinux.org>
sig revok  EAB08C4A 2017-09-10 __________ __________ [selfsig]
```

Then again, the key aren't used to for package signing (yet). So I think it is not on top priority...

**Comment by udeved** [comment]
@cromerc 

can you manage to get on irc today, tonight here?

**Comment by cromerc** [comment]
I believe so.

**Comment by cromerc** [comment]
I just signed nous's new key, it has to be resigned because he changed the email on his packager key. Also @udeved you signed the buildbot with your packager key, it needs to be signed with your master key for the web of trust to work.

**Pull request closed without merging**
